$ENV{'TEXINPUTS'}='./../../support//:' . $ENV{'TEXINPUTS'}; 
$ENV{'TEXINPUTS'}='./../../themes//:' . $ENV{'TEXINPUTS'}; 
$ENV{'OSFONTDIR'}="/usr/local/share/fonts;$HOME/.fonts;../../fonts";
#$pdflatex = "lualatex %O %S";
